version: '3'
services:
  time-tracker-web:
    build:
      context: ./time-tracker-web
      dockerfile: dockerfile.development
    ports:
      - "8080:8080"

  time-tracker-api:
    build:
      context: ./time-tracker-api
      dockerfile: dockerfile.development 
    ports:
      - "3000:3000"
    depends_on:
      - time-tracker-database