FROM node:18.13.0

WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install all dependencies
RUN npm install

# Copy the rest of your application source code
COPY . .

# Expose the port that the development server will run on
EXPOSE 8080 

# Start the development server
CMD ["npm", "run", "dev"]